version: '3'
services:
  erigon:
    image: thorax/erigon:v2022.08.01
    container_name: erigon
    command: /home/csx/docker-compose/erigon/config/erigon.sh
    volumes:
      - ./erigon_data:/work/data
      - ./config:/work/config
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 9090:9090
      - 8551:8551
    network_mode: host
  rpcdaemon:
    image: thorax/erigon:v2022.08.01
    container_name: erigon-rpc
    pid: service:erigon
    volumes:
      - ./config:/work/config
    restart: always
    command: /work/config/rpcdaemon.sh
    ports:
      - 8545:8545
      - 8546:8546
    network_mode: host
  lighthouse:
    image: sigp/lighthouse:v2.5.1
    container_name: lighthouse
    restart: always
    command: /work/config/lighthouse.sh
    volumes:
      - ./lighthouse_data:/work/data
      - ./config:/work/config
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 5052:5052
    network_mode: host
