version: '3'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server_1
    hostname: clickhouse-server_1
    networks:
      - test-bridge
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    expose:
      - 9009
    volumes:
      - ./config/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./config/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./data:/var/lib/clickhouse:rw
      - ./log:/var/log/clickhouse-server:rw

networks:
  test-bridge:
    driver: bridge
    ipam:
      driver: default