version: '3'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server_1
    hostname: clickhouse-server_1
    networks:
      - test-bridge
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    expose:
      - 9009
    volumes:
      - ./config/config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./data:/var/lib/clickhouse
      - ./log/clickhouse-server.log:/var/log/clickhouse-server/clickhouse-server.log
      - ./log/clickhouse-server.err.log:/var/log/clickhouse-server/clickhouse-server.err.log

networks:
  test-bridge:
    driver: bridge
    ipam:
      driver: default