version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper   
    ports:
      - "2181:2181"                 
  kafka:
    image: wurstmeister/kafka       
    volumes: 
        - /home/csx/docker-compose/kafka/etc/localtime:/etc/localtime
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.93.130   ## 宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181      
      KAFKA_ADVERTISED_PORT: 9092
  kafka-manager:  
    image: sheepkiller/kafka-manager                
    environment:
        ZK_HOSTS:  192.168.93.130                  ## zookeeper地址
    ports:  
      - "9001:9000"                                 # 宿主机port:container_port
